import { chromium } from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import assert from 'node:assert/strict';

const base = process.env.UI_BASE_URL;
assert(base && ['127.0.0.1', 'localhost'].includes(new URL(base).hostname), 'Browser tests require a loopback test host.');
const chrome = [process.env.CHROME_PATH, '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', '/usr/bin/google-chrome', '/usr/bin/chromium'].find(path => path && existsSync(path));
const browser = await chromium.launch({ executablePath: chrome });
const context = await browser.newContext({ viewport: { width: 1440, height: 960 }, reducedMotion: 'reduce' });
const page = await context.newPage();
page.setDefaultTimeout(12000);
const failures = [];
const checks = [];
const artifacts = 'tests/FantasyBasketball.IntegrationTests/TestResults/react-review';
await mkdir(artifacts, { recursive: true });
await context.route('**/*', route => new URL(route.request().url()).origin === new URL(base).origin ? route.continue() : route.abort());
page.on('pageerror', error => failures.push(error.message));
const visible = async locator => { await locator.waitFor({ state: 'visible' }); };
const enabled = async locator => { await visible(locator); await page.waitForFunction(element => !element.disabled, await locator.elementHandle()); };
async function accessibility(name) {
  const results = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze();
  assert.deepEqual(results.violations.map(item => ({ id: item.id, nodes: item.nodes.map(node => node.target) })), [], `${name} accessibility`);
  checks.push(`${name}: zero axe WCAG A/AA violations`);
}
try {
  await page.goto(new URL('/app', base).href);
  await visible(page.getByRole('button', { name: 'New here? Create an account' }));
  await accessibility('Account');
  await page.getByRole('button', { name: 'New here? Create an account' }).click();
  await page.getByLabel('Your name', { exact: true }).fill('Browser owner');
  await page.getByLabel('Email', { exact: true }).fill('browser@example.test');
  const fixturePassword = ['browser', 'fixture', 'long', 'password'].join(' ');
  await page.getByLabel('Password', { exact: true }).fill(fixturePassword);
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await visible(page.getByRole('heading', { name: 'Your rules. Your court.' }));
  assert.equal(await page.getByLabel('Teams', { exact: true }).inputValue(), '7');
  await accessibility('League setup');
  const denied = await page.evaluate(async () => (await fetch('/api/leagues', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' })).status);
  assert.equal(denied, 400, 'Cookie mutation without CSRF must fail');
  await page.getByLabel('League name').fill('Browser points league');
  await page.getByRole('button', { name: 'Add slot', exact: true }).click();
  await page.getByRole('button', { name: 'Add slot', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Use these reviewed scoring rules for my league.' }).check();
  await page.getByRole('button', { name: 'Save league' }).click();
  await visible(page.getByRole('heading', { name: 'Browser points league', exact: true }));
  await page.getByText('Prepare league projections', { exact: true }).click();
  const pool = page.getByLabel('Projection season and source', { exact: true });
  await visible(pool);
  await pool.selectOption({ index: 1 });
  await page.getByRole('button', { name: 'Calculate projections', exact: true }).click();
  await visible(page.getByText(/Saved estimates for 2 players/));
  await page.getByText('Prepare league projections', { exact: true }).click();
  await page.getByLabel('Your draft position', { exact: true }).fill('2');
  await page.getByLabel('Rounds', { exact: true }).fill('2');
  await page.getByRole('button', { name: 'Start draft' }).click();
  await visible(page.getByText('CURRENT PICK', { exact: true }));
  const shortlist = page.getByRole('region', { name: 'Next-pick shortlist' });
  await visible(shortlist.getByRole('button', { name: 'Fixture Guard', exact: true }));
  const originalAdvice = await shortlist.locator('.advice-list > li').evaluateAll(rows => rows.map(row => row.dataset.playerId));
  assert.equal(originalAdvice.length, 2);
  await shortlist.getByText('Why this pick', { exact: true }).first().click();
  await visible(shortlist.getByText(/Supporting:/).first());
  await shortlist.getByRole('button', { name: 'Fixture Guard', exact: true }).click();
  const projection = page.getByRole('region', { name: 'Fixture Guard projection' });
  await visible(projection.getByText(/Final fantasy points:/));
  await visible(projection.getByRole('columnheader', { name: 'Baseline', exact: true }));
  await visible(projection.getByRole('columnheader', { name: 'Adjusted', exact: true }));
  await projection.getByRole('button', { name: 'Close player details' }).click();
  const pick = page.getByRole('button', { name: 'Pick Fixture Guard', exact: true });
  await enabled(pick);
  const search = page.getByLabel('Find a player', { exact: true });
  await search.fill('Fixture Guard');
  await page.waitForResponse(response => response.url().includes('search=Fixture%20Guard') && response.status() === 200);
  await enabled(pick);
  const rowTop = await pick.evaluate(element => element.closest('tr').getBoundingClientRect().top + scrollY);
  await search.press('ArrowDown');
  assert.equal(await pick.evaluate(element => element === document.activeElement), true);
  await page.keyboard.press('Enter');
  await visible(page.getByRole('button', { name: 'Drafted Fixture Guard', exact: true }));
  await shortlist.getByRole('button', { name: 'Draft Fixture Guard', exact: true }).waitFor({ state: 'detached' });
  await visible(shortlist.getByRole('button', { name: 'Draft Fixture Center', exact: true }));
  const pickedTop = await page.getByRole('button', { name: 'Drafted Fixture Guard', exact: true }).evaluate(element => element.closest('tr').getBoundingClientRect().top + scrollY);
  assert(Math.abs(pickedTop - rowTop) < 1, `Player pool moved after a pick: ${pickedTop - rowTop}px`);
  checks.push('React player-pool row remains stationary after shortlist re-ranking');
  const savedUrl = page.url();
  assert(new URL(savedUrl).searchParams.get('draft'));
  await page.reload();
  await visible(page.getByRole('button', { name: 'Drafted Fixture Guard', exact: true }));
  assert.equal(await page.locator('.on-clock strong').textContent(), '2');
  await accessibility('Saved draft');
  await page.screenshot({ path: `${artifacts}/desktop.png`, fullPage: true });
  await page.getByRole('button', { name: 'Undo last pick', exact: true }).click();
  await enabled(pick);
  assert.equal(await page.locator('.on-clock strong').textContent(), '1');
  await page.reload();
  await enabled(pick);
  assert.equal(await page.locator('.on-clock strong').textContent(), '1');
  await enabled(shortlist.getByRole('button', { name: 'Draft Fixture Guard', exact: true }));
  assert.deepEqual(await shortlist.locator('.advice-list > li').evaluateAll(rows => rows.map(row => row.dataset.playerId)), originalAdvice);
  checks.push('Imported season → league projections → ranked advice, evidence and decomposition; pick removes recommendation, undo restores ordering');
  checks.push('Real cookie registration, CSRF rejection, seven-team league, snake draft, keyboard pick, reload persistence and undo');
  await page.getByText('Recorded performance · best & above baseline', { exact: true }).click();
  const performance = page.locator('details.performance');
  const results = performance.getByRole('region', { name: 'Recorded performance results' });
  await performance.getByLabel('Recorded season and source', { exact: true }).selectOption({ index: 1 });
  await performance.getByRole('button', { name: 'View performance', exact: true }).click();
  await visible(results.getByRole('heading', { name: 'Fixture Center', exact: true }));
  assert.equal(await results.locator('.performance-list > li h4').first().textContent(), 'Fixture Center');
  await performance.getByRole('button', { name: 'Above baseline', exact: true }).click();
  await visible(results.getByRole('heading', { name: 'Fixture Guard', exact: true }));
  assert.equal(await results.locator('.performance-list > li').count(), 1);
  await results.getByText('Games behind this result', { exact: true }).click();
  await visible(results.getByText('Comparison baseline · 10 appearances', { exact: true }));
  await visible(results.getByText('Recent sample · 3 appearances', { exact: true }));
  await results.locator('table').first().getByText('manual', { exact: true }).first().click();
  await visible(results.getByText(/SHA-256/).first());
  await results.getByText('Scoring used for these results', { exact: true }).click();
  await visible(results.getByText('PTS: 1 points per unit', { exact: true }));
  await accessibility('Recorded performance evidence');
  await performance.screenshot({ path: `${artifacts}/performance-desktop.png` });
  await performance.getByLabel('Games through', { exact: true }).fill('2026-01-04');
  await performance.getByRole('button', { name: 'View performance', exact: true }).click();
  await visible(results.getByText(/No players have a qualified positive lift/));
  await performance.getByRole('button', { name: 'All observed players', exact: true }).click();
  await visible(results.getByText(/Insufficient history for a heat comparison/).first());
  await performance.getByLabel('Games through', { exact: true }).fill('2025-12-31');
  await performance.getByRole('button', { name: 'View performance', exact: true }).click();
  await visible(results.getByText('No game observations match this source, season and date.', { exact: true }));
  await performance.getByLabel('Games through', { exact: true }).fill('2026-01-14');
  await page.route('**/performance?*', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ success: false, data: null, error: { code: 'source_unavailable', message: 'Fixture temporary failure', fields: {} }, meta: null }) }), { times: 1 });
  await performance.getByRole('button', { name: 'View performance', exact: true }).click();
  await visible(performance.getByRole('alert').filter({ hasText: 'Fixture temporary failure' }));
  await performance.getByRole('button', { name: 'Try again', exact: true }).click();
  await visible(results.getByRole('heading', { name: 'Fixture Guard', exact: true }));
  await performance.getByRole('button', { name: 'Above baseline', exact: true }).click();
  await visible(results.getByRole('heading', { name: 'Above baseline', exact: true }));
  await results.getByText('Games behind this result', { exact: true }).click();
  checks.push('Recorded games → separate best/above-baseline views, disjoint evidence, insufficient history, empty cutoff and failed-read retry');

  const leagueId = new URL(savedUrl).searchParams.get('league');
  await page.goto(new URL(`/app/drafts?league=${leagueId}`, base).href);
  await visible(page.getByRole('heading', { name: 'Your drafts', exact: true }));
  await visible(page.getByRole('link', { name: 'Reopen draft', exact: true }));
  await accessibility('Saved drafts');
  // Trailing slash on purpose: /app/<page>/ and /app/ must route like their bare forms.
  await page.goto(new URL(`/app/projections/?league=${leagueId}`, base).href);
  await visible(page.getByRole('heading', { name: 'Projected players', exact: true }));
  await visible(page.locator('table tbody tr').first());
  const projected = await page.locator('table tbody tr').evaluateAll(rows => rows.map(row => ({ rank: Number(row.cells[0].textContent), name: row.querySelector('th button').textContent, value: Number(row.cells[3].textContent.replace(/,/g, '')) })));
  assert.deepEqual(projected.map(row => row.rank), [1, 2]);
  assert.deepEqual(projected.map(row => row.name).sort(), ['Fixture Center', 'Fixture Guard']);
  assert(projected[0].value >= projected[1].value, `Projected players must be sorted by value: ${JSON.stringify(projected)}`);
  await accessibility('Projected players');
  await page.goto(new URL(`/app/?league=${leagueId}`, base).href);
  await visible(page.getByLabel('Your league', { exact: true }));
  checks.push('Projected players → league values ranked by season points; /app/ and /app/<page>/ route like their bare paths');
  await page.goto(new URL(`/app/league-settings?league=${leagueId}`, base).href);
  await visible(page.getByRole('heading', { name: 'League settings', exact: true }));
  assert.equal(await page.getByLabel('PG', { exact: true }).inputValue(), '2');
  await accessibility('League settings');
  await page.goto(new URL('/app/context-review', base).href);
  await visible(page.getByRole('heading', { name: 'Context review', exact: true }));
  await accessibility('Context review');
  await page.getByLabel('Find a player', { exact: true }).fill('Fixture Guard');
  await page.waitForResponse(response => response.url().includes('search=Fixture%20Guard') && response.status() === 200);
  await page.getByLabel('Player', { exact: true }).selectOption({ label: 'Fixture Guard' });
  await page.getByLabel('Effective from', { exact: true }).fill('2026-01-14');
  await page.getByLabel('Summary', { exact: true }).fill('Fixture injury review proposal');
  await page.getByRole('button', { name: 'Add proposal', exact: true }).click();
  await visible(page.getByText('Fixture injury review proposal', { exact: true }));
  await page.getByRole('button', { name: 'Verify', exact: true }).click();
  await visible(page.getByText('Injury · Verified', { exact: true }));
  await page.goto(new URL('/app/data-sources', base).href);
  await visible(page.getByRole('heading', { name: 'Data sources', exact: true }));
  assert.equal(await page.getByRole('button', { name: 'Import players', exact: true }).isEnabled(), true);
  await accessibility('Data sources');
  await page.goto(new URL('/app/account', base).href);
  await visible(page.getByRole('heading', { name: 'Account data', exact: true }));
  assert.equal(await page.getByRole('button', { name: 'Delete account', exact: true }).isEnabled(), false);
  await accessibility('Account data');
  for (const [path, heading] of [['trade-analyzer', 'Trade analyzer'], ['streaming', 'Streaming advisor'], ['standings', 'Standings']]) {
    await page.goto(new URL(`/app/${path}`, base).href);
    await visible(page.getByRole('heading', { name: heading, exact: true }));
    await accessibility(heading);
  }
  checks.push('Owner navigation reaches saved drafts, league settings, context review, imports, account data and explicit unsupported-capability pages');
  await page.goto(savedUrl);
  await enabled(page.getByRole('button', { name: 'Pick Fixture Guard', exact: true }));
  for (const width of [390, 320]) {
    await page.setViewportSize({ width, height: 844 });
    const overflow = await page.evaluate(() => ({ width: innerWidth, scroll: document.documentElement.scrollWidth, nodes: [...document.querySelectorAll('body *')].filter(element => { const box = element.getBoundingClientRect(); return box.right > innerWidth + 1 && getComputedStyle(element).position !== 'absolute' && !element.closest('.table-scroll'); }).map(element => ({ tag: element.tagName, class: element.className, width: element.getBoundingClientRect().width, right: element.getBoundingClientRect().right })) }));
    assert(overflow.scroll <= width, `${width}px document overflow: ${JSON.stringify(overflow)}`);
    await accessibility(`Draft and performance ${width}px`);
    await page.screenshot({ path: `${artifacts}/mobile-${width}.png`, fullPage: true });
  }
  await page.setViewportSize({ width: 390, height: 844 });
  for (const [path, heading] of [['/app/projections', 'Projected players'], ['/app/drafts', 'Your drafts'], ['/app/league-settings', 'League settings'], ['/app/context-review', 'Context review'], ['/app/data-sources', 'Data sources'], ['/app/account', 'Account data'], ['/app/trade-analyzer', 'Trade analyzer'], ['/app/streaming', 'Streaming advisor'], ['/app/standings', 'Standings'], ['/app/unknown', 'Page not found']]) {
    await page.goto(new URL(`${path}?league=${leagueId}`, base).href);
    await visible(page.getByRole('heading', { name: heading, exact: true }));
    const scrollWidth = await page.evaluate(() => document.documentElement.scrollWidth);
    assert(scrollWidth <= 390, `${path} overflows at 390px: ${scrollWidth}px`);
  }
  await page.goto(savedUrl);
  await enabled(page.getByRole('button', { name: 'Pick Fixture Guard', exact: true }));
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await visible(page.getByRole('heading', { name: 'Welcome back' }));
  assert((await page.evaluate(() => document.documentElement.scrollWidth)) <= 390, 'Landing overflows at 390px');
  await page.screenshot({ path: `${artifacts}/landing-390.png`, fullPage: true });
  assert.equal(await page.getByRole('button', { name: 'New here? Create an account' }).count(), 0);
  await page.getByLabel('Email', { exact: true }).fill('browser@example.test');
  await page.getByLabel('Password', { exact: true }).fill(fixturePassword);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await visible(page.getByLabel('Your league', { exact: true }));
  await page.goto(savedUrl);
  await enabled(pick);
  checks.push('Logout clears private state; closed registration stays hidden; login restores saved session');
  assert.deepEqual(failures, [], 'Browser runtime errors');
  await writeFile(`${artifacts}/report.json`, JSON.stringify({ passed: true, checks, failures }, null, 2));
  console.log(`React browser checks passed: ${checks.join('; ')}`);
} catch (error) {
  await page.screenshot({ path: `${artifacts}/failure.png`, fullPage: true });
  await writeFile(`${artifacts}/report.json`, JSON.stringify({ passed: false, checks, failures, error: String(error) }, null, 2));
  throw error;
} finally { await context.close(); await browser.close(); }
