import { chromium } from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import assert from 'node:assert/strict';

const base = process.env.UI_BASE_URL;
assert(base && ['127.0.0.1', 'localhost'].includes(new URL(base).hostname), 'Browser tests require a loopback test host.');
const chrome = [process.env.CHROME_PATH, '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', '/usr/bin/google-chrome', '/usr/bin/chromium'].find(path => path && existsSync(path));
const browser = await chromium.launch({ executablePath: chrome });
const context = await browser.newContext({ viewport: { width: 1440, height: 960 }, reducedMotion: 'reduce' });
const page = await context.newPage();
page.setDefaultTimeout(12000);
const failures = [];
const checks = [];
const artifacts = 'tests/FantasyBasketball.IntegrationTests/TestResults/react-review';
await mkdir(artifacts, { recursive: true });
await context.route('**/*', route => new URL(route.request().url()).origin === new URL(base).origin ? route.continue() : route.abort());
page.on('pageerror', error => failures.push(error.message));
const visible = async locator => { await locator.waitFor({ state: 'visible' }); };
const enabled = async locator => { await visible(locator); await page.waitForFunction(element => !element.disabled, await locator.elementHandle()); };
async function accessibility(name) {
  const results = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze();
  assert.deepEqual(results.violations.map(item => ({ id: item.id, nodes: item.nodes.map(node => node.target) })), [], `${name} accessibility`);
  checks.push(`${name}: zero axe WCAG A/AA violations`);
}
try {
  await page.goto(new URL('/app', base).href);
  await visible(page.getByRole('button', { name: 'New here? Create an account' }));
  await accessibility('Account');
  await page.getByRole('button', { name: 'New here? Create an account' }).click();
  await page.getByLabel('Your name', { exact: true }).fill('Browser owner');
  await page.getByLabel('Email', { exact: true }).fill('browser@example.test');
  const fixturePassword = ['browser', 'fixture', 'long', 'password'].join(' ');
  await page.getByLabel('Password', { exact: true }).fill(fixturePassword);
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await visible(page.getByRole('heading', { name: 'Your rules. Your court.' }));
  assert.equal(await page.getByLabel('Teams', { exact: true }).inputValue(), '7');
  await accessibility('League setup');
  const denied = await page.evaluate(async () => (await fetch('/api/leagues', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' })).status);
  assert.equal(denied, 400, 'Cookie mutation without CSRF must fail');
  await page.getByLabel('League name').fill('Browser points league');
  await page.getByRole('button', { name: 'Add slot', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Use these reviewed scoring rules for my league.' }).check();
  await page.getByRole('button', { name: 'Save league' }).click();
  await visible(page.getByRole('heading', { name: 'Browser points league', exact: true }));
  await page.getByLabel('Your draft position', { exact: true }).fill('2');
  await page.getByLabel('Rounds', { exact: true }).fill('2');
  await page.getByRole('button', { name: 'Start draft' }).click();
  await visible(page.getByText('CURRENT PICK', { exact: true }));
  const pick = page.getByRole('button', { name: 'Pick Fixture Guard', exact: true });
  await enabled(pick);
  const search = page.getByLabel('Find a player', { exact: true });
  await search.fill('Fixture Guard');
  await page.waitForResponse(response => response.url().includes('search=Fixture%20Guard') && response.status() === 200);
  await enabled(pick);
  await search.press('ArrowDown');
  assert.equal(await pick.evaluate(element => element === document.activeElement), true);
  await page.keyboard.press('Enter');
  await visible(page.getByRole('button', { name: 'Drafted Fixture Guard', exact: true }));
  const savedUrl = page.url();
  assert(new URL(savedUrl).searchParams.get('draft'));
  await page.reload();
  await visible(page.getByRole('button', { name: 'Drafted Fixture Guard', exact: true }));
  assert.equal(await page.locator('.on-clock strong').textContent(), '2');
  await accessibility('Saved draft');
  await page.screenshot({ path: `${artifacts}/desktop.png`, fullPage: true });
  await page.getByRole('button', { name: 'Undo last pick', exact: true }).click();
  await enabled(pick);
  assert.equal(await page.locator('.on-clock strong').textContent(), '1');
  await page.reload();
  await enabled(pick);
  assert.equal(await page.locator('.on-clock strong').textContent(), '1');
  checks.push('Real cookie registration, CSRF rejection, seven-team league, snake draft, keyboard pick, reload persistence and undo');
  for (const width of [390, 320]) {
    await page.setViewportSize({ width, height: 844 });
    const overflow = await page.evaluate(() => ({ width: innerWidth, scroll: document.documentElement.scrollWidth, nodes: [...document.querySelectorAll('body *')].filter(element => { const box = element.getBoundingClientRect(); return box.right > innerWidth + 1 && getComputedStyle(element).position !== 'absolute' && !element.closest('.table-scroll'); }).map(element => ({ tag: element.tagName, class: element.className, width: element.getBoundingClientRect().width, right: element.getBoundingClientRect().right })) }));
    assert(overflow.scroll <= width, `${width}px document overflow: ${JSON.stringify(overflow)}`);
    await accessibility(`Draft ${width}px`);
    await page.screenshot({ path: `${artifacts}/mobile-${width}.png`, fullPage: true });
  }
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await visible(page.getByRole('heading', { name: 'Welcome back' }));
  assert.equal(await page.getByRole('button', { name: 'New here? Create an account' }).count(), 0);
  await page.getByLabel('Email', { exact: true }).fill('browser@example.test');
  await page.getByLabel('Password', { exact: true }).fill(fixturePassword);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await visible(page.getByLabel('Your league', { exact: true }));
  await page.goto(savedUrl);
  await enabled(pick);
  checks.push('Logout clears private state; closed registration stays hidden; login restores saved session');
  assert.deepEqual(failures, [], 'Browser runtime errors');
  await writeFile(`${artifacts}/report.json`, JSON.stringify({ passed: true, checks, failures }, null, 2));
  console.log(`React browser checks passed: ${checks.join('; ')}`);
} catch (error) {
  await page.screenshot({ path: `${artifacts}/failure.png`, fullPage: true });
  await writeFile(`${artifacts}/report.json`, JSON.stringify({ passed: false, checks, failures, error: String(error) }, null, 2));
  throw error;
} finally { await context.close(); await browser.close(); }
