import { chromium } from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import assert from 'node:assert/strict';

const base = process.env.UI_BASE_URL;
assert(base && ['127.0.0.1', 'localhost'].includes(new URL(base).hostname), 'Browser tests require a loopback test host.');
const chrome = [process.env.CHROME_PATH, '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', '/usr/bin/google-chrome', '/usr/bin/chromium'].find(path => path && existsSync(path));
const browser = await chromium.launch({ executablePath: chrome });
const context = await browser.newContext({ viewport: { width: 1440, height: 960 }, reducedMotion: 'reduce' });
const page = await context.newPage();
page.setDefaultTimeout(12000);
const failures = [];
const checks = [];
const artifacts = 'tests/FantasyBasketball.IntegrationTests/TestResults/react-review';
await mkdir(artifacts, { recursive: true });
await context.route('**/*', route => new URL(route.request().url()).origin === new URL(base).origin ? route.continue() : route.abort());
page.on('pageerror', error => failures.push(error.message));
const visible = async locator => { await locator.waitFor({ state: 'visible' }); };
const enabled = async locator => { await visible(locator); await page.waitForFunction(element => !element.disabled, await locator.elementHandle()); };
async function accessibility(name) {
  const results = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze();
  assert.deepEqual(results.violations.map(item => ({ id: item.id, nodes: item.nodes.map(node => node.target) })), [], `${name} accessibility`);
  checks.push(`${name}: zero axe WCAG A/AA violations`);
}
// Landing with mocked public data: the test host stores no Basketball-Reference games.
const envelope = data => ({ success: true, data, error: null, meta: null });
const dailyFixture = envelope({ date: '2025-11-16', source: 'basketball-reference', scoring: 'ESPN default points', poolSize: 168, simulatedToday: '2025-11-17', players: [
  { playerId: 'p1', name: 'Luka Dončić', playedOn: '2025-11-16', minutes: 36, fantasyPoints: 65.5, categoriesWon: 7, line: { PTS: 38, REB: 9, AST: 11 } },
  { playerId: 'p2', name: 'Fixture Newcomer', playedOn: '2025-11-14', minutes: 30, fantasyPoints: 30, categoriesWon: 4, line: { PTS: 20, REB: 5, AST: 3 } }] });
const risersFixture = envelope({ throughDate: '2025-12-15', source: 'basketball-reference', scoring: 'ESPN default points', players: Array.from({ length: 12 }, (_, index) => (
  { playerId: `r${index}`, name: `Riser ${index + 1}`, latestAppearance: '2025-12-15', categoriesWon: 5, recentAverage: 30 - index, baselineAverage: 18, streak: 3, percentAboveBaseline: 66.7, status: index === 0 ? 'Must add' : 'Add' })) });
async function landingPage(reducedMotion, width = 1280) {
  const landingContext = await browser.newContext({ viewport: { width, height: 900 }, reducedMotion });
  await landingContext.route('**/*', route => {
    const url = new URL(route.request().url());
    if (url.origin !== new URL(base).origin) return route.abort();
    if (url.pathname === '/api/public/daily') return route.fulfill({ json: dailyFixture });
    if (url.pathname === '/api/public/risers') return route.fulfill({ json: risersFixture });
    return route.continue();
  });
  const landing = await landingContext.newPage();
  landing.setDefaultTimeout(12000);
  landing.on('pageerror', error => failures.push(error.message));
  await landing.goto(new URL('/', base).href);
  return landing;
}
async function landingChecks() {
  const landing = await landingPage('no-preference');
  const strip = landing.getByRole('region', { name: 'How the stars played.' });
  const cards = strip.locator('.player-card:not([aria-hidden])');
  await visible(cards.getByText('Luka Dončić', { exact: true }));
  assert.equal(await cards.count(), 2);
  assert.equal(await strip.locator('.player-card[aria-hidden=true]').count(), 2, 'the loop copy exists but is hidden from assistive tech');
  await visible(cards.getByText('7/9', { exact: true }));
  await visible(cards.getByText('65.5', { exact: true }));
  await visible(cards.getByText('Nov 14', { exact: true }));
  assert.equal(await cards.first().locator('.pc-date').count(), 0, 'a game on the shown day carries no date chip');
  const track = strip.locator('.marquee-track');
  assert.equal(await track.evaluate(element => getComputedStyle(element).animationPlayState), 'running');
  await strip.getByRole('button', { name: 'Pause rotation' }).click();
  assert.equal(await strip.getByRole('button', { name: 'Play rotation' }).getAttribute('aria-pressed'), 'true');
  assert.equal(await track.evaluate(element => getComputedStyle(element).animationPlayState), 'paused');
  await visible(landing.getByText('PREVIOUS GAME DAY · SUNDAY, NOV 16, 2025'));
  await visible(landing.getByRole('note').filter({ hasText: 'Replaying the 2025–26 season as if today were Monday, Nov 17, 2025' }));
  const photo = cards.locator('img');
  assert.equal(await photo.count(), 1, 'only players with a credited photo get an image');
  await photo.scrollIntoViewIfNeeded();
  await landing.waitForFunction(element => element.complete && element.naturalWidth > 0, await photo.elementHandle());
  await visible(cards.getByText('FN', { exact: true }));
  const rows = landing.locator('.risers-table tbody tr');
  assert.equal(await rows.count(), 12);
  assert.equal(await rows.last().evaluate(row => row.classList.contains('in')), false, 'rows below the fold wait to rise');
  await rows.last().scrollIntoViewIfNeeded();
  await landing.waitForFunction(() => document.querySelector('.risers-table tbody tr:last-child').classList.contains('in'));
  await visible(landing.getByRole('row', { name: /Riser 1 .*Must add/ }));
  await landing.evaluate(() => scrollTo(0, 0));
  await landing.waitForFunction(() => !document.querySelector('.risers-table tbody tr:last-child').classList.contains('in'));
  const results = await new AxeBuilder({ page: landing }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze();
  assert.deepEqual(results.violations.map(item => ({ id: item.id, nodes: item.nodes.map(node => node.target) })), [], 'Landing accessibility');
  await landing.screenshot({ path: `${artifacts}/landing-desktop.png`, fullPage: true });
  await landing.context().close();
  const still = await landingPage('reduce');
  await visible(still.getByRole('row', { name: /Riser 12/ }));
  assert.equal(await still.locator('.player-card[aria-hidden=true]').first().isVisible(), false, 'no loop copy without motion');
  assert.equal(await still.getByRole('button', { name: 'Pause rotation' }).isVisible(), false);
  assert.equal(await still.locator('.marquee-track').evaluate(element => getComputedStyle(element).animationName), 'none');
  assert.equal(await still.locator('.risers-table tbody tr.in').count(), 12, 'reduced motion shows every row in place');
  await still.context().close();
  for (const width of [390, 320]) {
    const narrow = await landingPage('reduce', width);
    await visible(narrow.locator('.player-card:not([aria-hidden])').getByText('Luka Dončić', { exact: true }));
    await visible(narrow.getByRole('row', { name: /Riser 1 / }));
    const scroll = await narrow.evaluate(() => document.documentElement.scrollWidth);
    assert(scroll <= width, `Landing overflows at ${width}px: ${scroll}px`);
    const narrowAxe = await new AxeBuilder({ page: narrow }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze();
    assert.deepEqual(narrowAxe.violations.map(item => ({ id: item.id, nodes: item.nodes.map(node => node.target) })), [], `Landing accessibility ${width}px`);
    await narrow.screenshot({ path: `${artifacts}/landing-mobile-${width}.png`, fullPage: true });
    await narrow.context().close();
  }
  checks.push('Landing: continuously rotating featured cards (hidden loop copy, pause control, dated earlier games) with credited photo and initials fallback, CAT and ESPN points, rows rise on scroll and reset below the fold, still under reduced motion, axe clean, no overflow at 390/320 px');
}
try {
  await landingChecks();
  await page.goto(new URL('/app', base).href);
  await visible(page.getByRole('button', { name: 'New here? Create an account' }));
  await accessibility('Account');
  await page.getByRole('button', { name: 'New here? Create an account' }).click();
  await page.getByLabel('Your name', { exact: true }).fill('Browser owner');
  await page.getByLabel('Email', { exact: true }).fill('browser@example.test');
  const fixturePassword = ['browser', 'fixture', 'long', 'password'].join(' ');
  await page.getByLabel('Password', { exact: true }).fill(fixturePassword);
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await visible(page.getByRole('heading', { name: 'What do you want to see?', exact: true }));
  const menu = page.locator('.hub-list');
  assert.deepEqual(await menu.locator('.hub-label').evaluateAll(labels => labels.map(label => label.firstChild.textContent)),
    ['Mock draft', 'Teams in the league', 'Waiver wire analyzer', 'Projected players', 'Your drafts', 'Trade analyzer', 'Matchup analyzer', 'Streaming advisor', 'League settings', 'Context review', 'Account data', 'Data sources']);
  assert.equal(await menu.locator('.hub-soon').count(), 0);
  assert.equal(await page.getByText(/coming soon/i).count(), 0, 'D-33: unbuilt pages never say "coming soon"');
  await accessibility('Signed-in menu');
  await page.screenshot({ path: `${artifacts}/menu-desktop.png`, fullPage: true });
  await page.getByRole('link', { name: /^Mock draft/ }).click();
  await page.waitForURL(url => url.pathname === '/app/draft');
  await visible(page.getByRole('heading', { name: 'Your rules. Your court.' }));
  checks.push('Sign-in lands on the oval-button menu; Mock draft opens the draft workspace at /app/draft');
  assert.equal(await page.getByLabel('Teams', { exact: true }).inputValue(), '10');
  assert.equal(await page.getByLabel('UTIL', { exact: true }).inputValue(), '3', 'the standard roster is prefilled');
  assert.equal(await page.getByLabel('Weekly acquisitions', { exact: true }).inputValue(), '7');
  await accessibility('League setup');
  const denied = await page.evaluate(async () => (await fetch('/api/leagues', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' })).status);
  assert.equal(denied, 400, 'Cookie mutation without CSRF must fail');
  await page.getByLabel('League name').fill('Browser points league');
  await page.getByRole('checkbox', { name: 'Use these reviewed scoring rules for my league.' }).check();
  await page.getByRole('button', { name: 'Save league' }).click();
  await visible(page.getByRole('heading', { name: 'Browser points league', exact: true }));
  await page.getByText('Prepare league projections', { exact: true }).click();
  const pool = page.getByLabel('Projection season and source', { exact: true });
  await visible(pool);
  await pool.selectOption({ index: 1 });
  await page.getByRole('button', { name: 'Calculate projections', exact: true }).click();
  await visible(page.getByText(/Saved estimates for 2 players/));
  await page.getByText('Prepare league projections', { exact: true }).click();
  await page.getByLabel('Your draft position', { exact: true }).fill('1');
  await page.getByLabel('Rounds', { exact: true }).fill('2');
  await page.getByRole('button', { name: 'Start draft' }).click();
  await visible(page.getByText('YOUR PICK', { exact: true }));
  assert.equal(await page.getByRole('button', { name: 'Sim other teams to my pick', exact: true }).isDisabled(), true, 'never simulates the user\'s own pick');
  const shortlist = page.getByRole('region', { name: 'Next-pick shortlist' });
  await visible(shortlist.getByRole('button', { name: 'Fixture Guard', exact: true }));
  const originalAdvice = await shortlist.locator('.advice-list > li').evaluateAll(rows => rows.map(row => row.dataset.playerId));
  assert.equal(originalAdvice.length, 2);
  const simulated = page.getByRole('region', { name: 'Simulated pick' });
  await visible(simulated.getByText(/fitted models active/));
  const fixtureIds = Object.fromEntries(await shortlist.locator('.advice-list > li').evaluateAll(rows => rows.map(row => [row.querySelector('.player-name')?.textContent, row.dataset.playerId])));
  const simulationRequests = [];
  await page.route('**/board/simulation?*', route => {
    simulationRequests.push(new URL(route.request().url()).searchParams.get('risk'));
    route.fulfill({ json: envelope({ unavailable: null, board: { mode: 1, rollouts: 500, nextUserPick: 14, candidates: [
      { playerId: { value: fixtureIds['Fixture Center'] }, mean: 21450, sd: 1830, p10: 19100, p90: 23800, score: 20535, edge: 0, edgeSe: 0, survivalToNextPick: 0.12 },
      { playerId: { value: fixtureIds['Fixture Guard'] }, mean: 21010, sd: 1610, p10: 18900, p90: 23050, score: 20205, edge: -440, edgeSe: 85, survivalToNextPick: 0.35 }] } }) });
  });
  await simulated.getByLabel('Safer', { exact: true }).check();
  const card = simulated.getByRole('article', { name: 'Top simulated pick' });
  await visible(card.getByRole('heading', { name: 'Fixture Center', exact: true }));
  await visible(card.getByText(/Likely gone before your pick 14: about 12% chance he lasts\./));
  await visible(card.getByText('+440', { exact: true }));
  assert.equal(await simulated.locator('.sim-board > li .interval-range').count(), 2);
  await visible(simulated.getByText('35% at pick 14', { exact: true }));
  assert(simulationRequests.includes('cautious'), `risk toggle did not request cautious: ${simulationRequests}`);
  assert.equal(await page.evaluate(() => localStorage.getItem('fb.draftRisk')), 'cautious');
  await accessibility('Simulated pick');
  await simulated.screenshot({ path: `${artifacts}/simulation-desktop.png` });
  await page.setViewportSize({ width: 390, height: 844 });
  assert((await page.evaluate(() => document.documentElement.scrollWidth)) <= 390, 'Simulated pick overflows at 390px');
  await simulated.screenshot({ path: `${artifacts}/simulation-390.png` });
  await page.setViewportSize({ width: 1440, height: 960 });
  await simulated.getByLabel('Best average', { exact: true }).check();
  await page.unroute('**/board/simulation?*');
  // Back to the real (unavailable) panel before picking, so the pick does not swap a mocked board out.
  await page.reload();
  await visible(simulated.getByText(/fitted models active/));
  checks.push('Simulated pick: honest unavailable notice, then pick card (edge ± SE, one-line reason), interval bars and survival odds; risk toggle re-simulates and is remembered; axe clean; no overflow at 390px');
  await shortlist.getByText('Why this pick', { exact: true }).first().click();
  await visible(shortlist.getByText(/Supporting:/).first());
  await shortlist.getByRole('button', { name: 'Fixture Guard', exact: true }).click();
  const projection = page.getByRole('region', { name: 'Fixture Guard projection' });
  await visible(projection.getByText(/Final fantasy points:/));
  await visible(projection.getByRole('columnheader', { name: 'Baseline', exact: true }));
  await visible(projection.getByRole('columnheader', { name: 'Adjusted', exact: true }));
  await projection.getByRole('button', { name: 'Close player details' }).click();
  const pick = page.getByRole('button', { name: 'Pick Fixture Guard', exact: true });
  await enabled(pick);
  const search = page.getByLabel('Find a player', { exact: true });
  await search.fill('Fixture Guard');
  await page.waitForResponse(response => response.url().includes('search=Fixture%20Guard') && response.status() === 200);
  await enabled(pick);
  const rowTop = await pick.evaluate(element => element.closest('tr').getBoundingClientRect().top + scrollY);
  await search.press('ArrowDown');
  assert.equal(await pick.evaluate(element => element === document.activeElement), true);
  await page.keyboard.press('Enter');
  await visible(page.getByRole('button', { name: 'Drafted Fixture Guard', exact: true }));
  await shortlist.getByRole('button', { name: 'Draft Fixture Guard', exact: true }).waitFor({ state: 'detached' });
  await visible(shortlist.getByRole('button', { name: 'Draft Fixture Center', exact: true }));
  const pickedTop = await page.getByRole('button', { name: 'Drafted Fixture Guard', exact: true }).evaluate(element => element.closest('tr').getBoundingClientRect().top + scrollY);
  assert(Math.abs(pickedTop - rowTop) < 1, `Player pool moved after a pick: ${pickedTop - rowTop}px`);
  checks.push('React player-pool row remains stationary after shortlist re-ranking');
  const savedUrl = page.url();
  assert(new URL(savedUrl).searchParams.get('draft'));
  await page.reload();
  await visible(page.getByRole('button', { name: 'Drafted Fixture Guard', exact: true }));
  assert.equal(await page.locator('.on-clock strong').textContent(), '2');
  await accessibility('Saved draft');
  await page.screenshot({ path: `${artifacts}/desktop.png`, fullPage: true });
  await page.getByRole('button', { name: 'Undo last pick', exact: true }).click();
  await enabled(pick);
  assert.equal(await page.locator('.on-clock strong').textContent(), '1');
  await page.reload();
  await enabled(pick);
  assert.equal(await page.locator('.on-clock strong').textContent(), '1');
  await enabled(shortlist.getByRole('button', { name: 'Draft Fixture Guard', exact: true }));
  assert.deepEqual(await shortlist.locator('.advice-list > li').evaluateAll(rows => rows.map(row => row.dataset.playerId)), originalAdvice);
  checks.push('Imported season → league projections → ranked advice, evidence and decomposition; pick removes recommendation, undo restores ordering');
  checks.push('Real cookie registration, CSRF rejection, seven-team league, snake draft, keyboard pick, reload persistence and undo');
  await page.getByText('Recorded performance · best & above baseline', { exact: true }).click();
  const performance = page.locator('details.performance');
  const results = performance.getByRole('region', { name: 'Recorded performance results' });
  await performance.getByLabel('Recorded season and source', { exact: true }).selectOption({ index: 1 });
  await performance.getByRole('button', { name: 'View performance', exact: true }).click();
  await visible(results.getByRole('heading', { name: 'Fixture Center', exact: true }));
  assert.equal(await results.locator('.performance-list > li h4').first().textContent(), 'Fixture Center');
  await performance.getByRole('button', { name: 'Above baseline', exact: true }).click();
  await visible(results.getByRole('heading', { name: 'Fixture Guard', exact: true }));
  assert.equal(await results.locator('.performance-list > li').count(), 1);
  await results.getByText('Games behind this result', { exact: true }).click();
  await visible(results.getByText('Comparison baseline · 10 appearances', { exact: true }));
  await visible(results.getByText('Recent sample · 3 appearances', { exact: true }));
  await results.locator('table').first().getByText('manual', { exact: true }).first().click();
  await visible(results.getByText(/SHA-256/).first());
  await results.getByText('Scoring used for these results', { exact: true }).click();
  await visible(results.getByText('PTS: 1 points per unit', { exact: true }));
  await accessibility('Recorded performance evidence');
  await performance.screenshot({ path: `${artifacts}/performance-desktop.png` });
  await performance.getByLabel('Games through', { exact: true }).fill('2026-01-04');
  await performance.getByRole('button', { name: 'View performance', exact: true }).click();
  await visible(results.getByText(/No players have a qualified positive lift/));
  await performance.getByRole('button', { name: 'All observed players', exact: true }).click();
  await visible(results.getByText(/Insufficient history for a heat comparison/).first());
  await performance.getByLabel('Games through', { exact: true }).fill('2025-12-31');
  await performance.getByRole('button', { name: 'View performance', exact: true }).click();
  await visible(results.getByText('No game observations match this source, season and date.', { exact: true }));
  await performance.getByLabel('Games through', { exact: true }).fill('2026-01-14');
  await page.route('**/performance?*', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ success: false, data: null, error: { code: 'source_unavailable', message: 'Fixture temporary failure', fields: {} }, meta: null }) }), { times: 1 });
  await performance.getByRole('button', { name: 'View performance', exact: true }).click();
  await visible(performance.getByRole('alert').filter({ hasText: 'Fixture temporary failure' }));
  await performance.getByRole('button', { name: 'Try again', exact: true }).click();
  await visible(results.getByRole('heading', { name: 'Fixture Guard', exact: true }));
  await performance.getByRole('button', { name: 'Above baseline', exact: true }).click();
  await visible(results.getByRole('heading', { name: 'Above baseline', exact: true }));
  await results.getByText('Games behind this result', { exact: true }).click();
  checks.push('Recorded games → separate best/above-baseline views, disjoint evidence, insufficient history, empty cutoff and failed-read retry');

  const guardId = await results.locator('.performance-list > li').first().getAttribute('data-player-id');
  const disclaimer = 'Describes the last 5 games against the 10–30 before them. Not a forecast. About 5% of players get a label like this by chance alone.';
  await page.route('**/heat-labels?*', route => route.fulfill({ json: envelope({ seasonEndYear: 2026, throughDate: '2026-01-14', modelVersion: 'heat-prior-fixture', eligiblePlayers: 40, qualifiedPlayers: 32, nullLabelRate: 0.05, expectedChanceLabels: 0, disclaimer,
    labels: [{ playerId: guardId, label: 'HOT', cause: 'Role', probability: 0.83, shiftMean: 6.2, shiftLow: 2.9, shiftHigh: 9.5, opportunityShare: 0.71, recentGames: 5, baselineGames: 8, throughDate: '2026-01-14' }] }) }));
  await performance.getByRole('button', { name: 'View performance', exact: true }).click();
  await performance.getByRole('button', { name: 'Hot & cold', exact: true }).click();
  const heatLabels = performance.getByRole('region', { name: 'Hot and cold labels' });
  await visible(heatLabels.getByText('HOT · Role', { exact: true }));
  await visible(heatLabels.getByText('That is about 0 of the 1 labels below.', { exact: false }));
  assert.match(await heatLabels.locator('.heat-badge').first().getAttribute('title'), /Not a forecast/);
  await accessibility('Hot and cold labels');
  await performance.screenshot({ path: `${artifacts}/heat-labels-desktop.png` });
  await performance.getByRole('button', { name: 'Above baseline', exact: true }).click();
  await visible(results.locator('.performance-list .heat-badge.hot'));
  await visible(results.locator('svg.game-chart'));
  await page.unroute('**/heat-labels?*');
  checks.push('Hot & cold view shows the chance banner and a disclaimed HOT · Role badge; the badge and game chart reach the performance rows');

  const leagueId = new URL(savedUrl).searchParams.get('league');
  await page.goto(new URL(`/app/drafts?league=${leagueId}`, base).href);
  await visible(page.getByRole('heading', { name: 'Your drafts', exact: true }));
  await visible(page.getByRole('link', { name: 'Reopen draft', exact: true }));
  await accessibility('Saved drafts');
  // Trailing slash on purpose: /app/<page>/ and /app/ must route like their bare forms.
  await page.goto(new URL(`/app/projections/?league=${leagueId}`, base).href);
  await visible(page.getByRole('heading', { name: 'Projected players', exact: true }));
  await visible(page.locator('table tbody tr').first());
  const projected = await page.locator('table tbody tr').evaluateAll(rows => rows.map(row => ({ rank: Number(row.cells[0].textContent), name: row.querySelector('th button').textContent, value: Number(row.cells[3].textContent.replace(/,/g, '')) })));
  assert.deepEqual(projected.map(row => row.rank), [1, 2]);
  assert.deepEqual(projected.map(row => row.name).sort(), ['Fixture Center', 'Fixture Guard']);
  assert(projected[0].value >= projected[1].value, `Projected players must be sorted by value: ${JSON.stringify(projected)}`);
  await accessibility('Projected players');
  await page.goto(new URL('/', base).href);
  await visible(page.getByRole('heading', { name: 'What do you want to see?', exact: true }));
  await page.goto(new URL(`/app/?league=${leagueId}`, base).href);
  await visible(page.getByRole('heading', { name: 'What do you want to see?', exact: true }));
  assert.equal(await page.getByRole('link', { name: /^Projected players/ }).getAttribute('href'), `/app/projections?league=${leagueId}`, 'menu links keep the league');
  await page.goto(new URL(`/app/draft/?league=${leagueId}`, base).href);
  await visible(page.getByLabel('Your league', { exact: true }));
  checks.push('Projected players → league values ranked by season points; /app/ and /app/<page>/ route like their bare paths');
  await page.goto(new URL(`/app/teams?league=${leagueId}`, base).href);
  await visible(page.getByText('No rosters yet.', { exact: false }));
  // Offline: the Sleeper panel is present and only enables once a league id is recognised; it is never sent.
  const sleeperPreview = page.getByRole('button', { name: 'Preview league' });
  assert.equal(await sleeperPreview.isEnabled(), false);
  await page.getByLabel('Sleeper league link or ID').fill('https://sleeper.com/leagues/1000000000000000001/league');
  assert.equal(await sleeperPreview.isEnabled(), true);
  await page.getByLabel('Sleeper league link or ID').fill('');
  await page.getByLabel('Roster CSV').fill('Team,Player,Mine\nBrowser Squad,Fixture Guard,yes\nRivals,Fixture Center,\nRivals,Nobody Real,');
  await page.getByRole('button', { name: /Import rosters/ }).click();
  await visible(page.getByRole('status').filter({ hasText: 'Imported 2 teams and 2 players.' }));
  await visible(page.getByText('Nobody Real (line 4)', { exact: false }));
  await visible(page.getByRole('article', { name: 'Browser Squad' }).getByText('Your team', { exact: true }));
  await visible(page.getByRole('article', { name: 'Rivals' }).getByText('Fixture Center', { exact: true }));
  await accessibility('League rosters');
  await page.screenshot({ path: `${artifacts}/teams-desktop.png`, fullPage: true });
  checks.push('Teams: CSV roster import with unmatched-name report, your-team badge, axe clean');
  await page.goto(new URL(`/app/waiver?league=${leagueId}`, base).href);
  await visible(page.getByText('The 2 players on your league’s rosters are left out.', { exact: false }));
  checks.push('League waiver: scored under the league, leaving out rostered players');
  await page.goto(new URL(`/app/matchup?league=${leagueId}`, base).href);
  await visible(page.getByRole('heading', { name: 'Browser Squad vs Rivals' }));
  await visible(page.getByRole('region', { name: 'Browser Squad players' }).getByText('Fixture Guard', { exact: true }));
  await accessibility('Weekly matchup');
  await page.screenshot({ path: `${artifacts}/matchup-desktop.png`, fullPage: true });
  checks.push('Matchup: your team against a league opponent with scored-so-far plus projected rest of week');
  await page.goto(new URL(`/app/streaming?league=${leagueId}`, base).href);
  await visible(page.getByRole('heading', { name: /move|Hold your roster/ }));
  await visible(page.getByText('How this plan was made', { exact: true }));
  await accessibility('Streaming plan');
  checks.push('Streaming: dated add/drop plan (or an explained hold) for the league');
  await page.goto(new URL(`/app/trade-analyzer?league=${leagueId}`, base).href);
  await page.getByRole('checkbox', { name: 'Rivals' }).check();
  await page.getByRole('group', { name: /You send/ }).getByRole('checkbox', { name: 'Fixture Guard' }).check();
  await page.getByRole('group', { name: 'You receive from Rivals' }).getByRole('checkbox', { name: 'Fixture Center' }).check();
  await page.getByRole('button', { name: /Evaluate trade/ }).click();
  await visible(page.getByRole('heading', { name: /season points/ }));
  await visible(page.getByText('This judges what the trade does to your team, not whether it is fair to the other manager.'));
  await accessibility('Trade analyzer');
  await page.screenshot({ path: `${artifacts}/trade-desktop.png`, fullPage: true });
  checks.push('Trade: two-team trade evaluated for your side with verdict, lineup before/after and evidence');
  await page.goto(new URL(`/app/league-settings?league=${leagueId}`, base).href);
  await visible(page.getByRole('heading', { name: 'League settings', exact: true }));
  assert.equal(await page.getByLabel('PG', { exact: true }).inputValue(), '2');
  await accessibility('League settings');
  await page.goto(new URL('/app/context-review', base).href);
  await visible(page.getByRole('heading', { name: 'Context review', exact: true }));
  await accessibility('Context review');
  await page.getByLabel('Find a player', { exact: true }).fill('Fixture Guard');
  await page.waitForResponse(response => response.url().includes('search=Fixture%20Guard') && response.status() === 200);
  await page.getByLabel('Player', { exact: true }).selectOption({ label: 'Fixture Guard' });
  await page.getByLabel('Effective from', { exact: true }).fill('2026-01-14');
  await page.getByLabel('Summary', { exact: true }).fill('Fixture injury review proposal');
  await page.getByRole('button', { name: 'Add proposal', exact: true }).click();
  await visible(page.getByText('Fixture injury review proposal', { exact: true }));
  await page.getByRole('button', { name: 'Verify', exact: true }).click();
  await visible(page.getByText('Injury · Verified', { exact: true }));
  await page.goto(new URL('/app/data-sources', base).href);
  await visible(page.getByRole('heading', { name: 'Data sources', exact: true }));
  assert.equal(await page.getByRole('button', { name: 'Import players', exact: true }).isEnabled(), true);
  // Offline test: the box-score action is present and enabled, never clicked.
  assert.equal(await page.getByRole('group', { name: 'Box scores (Basketball-Reference)' }).getByRole('button', { name: 'Import box scores' }).isEnabled(), true);
  await accessibility('Data sources');
  await page.goto(new URL('/app/account', base).href);
  await visible(page.getByRole('heading', { name: 'Account data', exact: true }));
  assert.equal(await page.getByRole('button', { name: 'Delete account', exact: true }).isEnabled(), false);
  await accessibility('Account data');
  for (const [path, heading] of [['trade-analyzer', 'Trade analyzer'], ['streaming', 'Streaming advisor'], ['standings', 'Standings'], ['matchup', 'Matchup analyzer'], [`waiver?league=${leagueId}`, 'Rising right now.']]) {
    await page.goto(new URL(`/app/${path}`, base).href);
    await visible(page.getByRole('heading', { name: new RegExp(`^${heading.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\.?$`) }).first());
    await accessibility(heading);
  }
  checks.push('Owner navigation reaches saved drafts, league settings, context review, imports, account data and explicit unsupported-capability pages');
  await page.goto(savedUrl);
  await enabled(page.getByRole('button', { name: 'Pick Fixture Guard', exact: true }));
  for (const width of [390, 320]) {
    await page.setViewportSize({ width, height: 844 });
    const overflow = await page.evaluate(() => ({ width: innerWidth, scroll: document.documentElement.scrollWidth, nodes: [...document.querySelectorAll('body *')].filter(element => { const box = element.getBoundingClientRect(); return box.right > innerWidth + 1 && getComputedStyle(element).position !== 'absolute' && !element.closest('.table-scroll'); }).map(element => ({ tag: element.tagName, class: element.className, width: element.getBoundingClientRect().width, right: element.getBoundingClientRect().right })) }));
    assert(overflow.scroll <= width, `${width}px document overflow: ${JSON.stringify(overflow)}`);
    await accessibility(`Draft and performance ${width}px`);
    await page.screenshot({ path: `${artifacts}/mobile-${width}.png`, fullPage: true });
  }
  await page.setViewportSize({ width: 390, height: 844 });
  for (const [path, name] of [['/app', 'menu'], [`/app/teams?league=${leagueId}`, 'teams'], [`/app/matchup?league=${leagueId}`, 'matchup']]) {
    await page.goto(new URL(path, base).href);
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: `${artifacts}/${name}-390.png`, fullPage: true });
  }
  for (const [path, heading] of [['/app/projections', 'Projected players'], ['/app/drafts', 'Your drafts'], ['/app/league-settings', 'League settings'], ['/app/context-review', 'Context review'], ['/app/data-sources', 'Data sources'], ['/app/account', 'Account data'], ['/app/trade-analyzer', 'Trade analyzer'], ['/app/streaming', 'Streaming advisor'], ['/app/standings', 'Standings'], ['/app/waiver', 'Rising right now.'], ['/app/matchup', 'Matchup analyzer'], ['/app/teams', 'Teams in the league'], ['/app', 'What do you want to see?'], ['/app/unknown', 'Page not found']]) {
    await page.goto(new URL(`${path}?league=${leagueId}`, base).href);
    await visible(page.getByRole('heading', { name: new RegExp(`^${heading.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\.?$`) }).first());
    const scrollWidth = await page.evaluate(() => document.documentElement.scrollWidth);
    assert(scrollWidth <= 390, `${path} overflows at 390px: ${scrollWidth}px`);
  }
  await page.goto(savedUrl);
  await enabled(page.getByRole('button', { name: 'Pick Fixture Guard', exact: true }));
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await visible(page.getByRole('heading', { name: 'Welcome back' }));
  assert((await page.evaluate(() => document.documentElement.scrollWidth)) <= 390, 'Landing overflows at 390px');
  await page.screenshot({ path: `${artifacts}/landing-390.png`, fullPage: true });
  assert.equal(await page.getByRole('button', { name: 'New here? Create an account' }).count(), 0);
  await page.getByLabel('Email', { exact: true }).fill('browser@example.test');
  await page.getByLabel('Password', { exact: true }).fill(fixturePassword);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await visible(page.getByRole('heading', { name: 'What do you want to see?', exact: true }));
  await page.goto(savedUrl);
  await enabled(pick);
  checks.push('Logout clears private state; closed registration stays hidden; login restores saved session');
  assert.deepEqual(failures, [], 'Browser runtime errors');
  await writeFile(`${artifacts}/report.json`, JSON.stringify({ passed: true, checks, failures }, null, 2));
  console.log(`React browser checks passed: ${checks.join('; ')}`);
} catch (error) {
  await page.screenshot({ path: `${artifacts}/failure.png`, fullPage: true });
  await writeFile(`${artifacts}/report.json`, JSON.stringify({ passed: false, checks, failures, error: String(error) }, null, 2));
  throw error;
} finally { await context.close(); await browser.close(); }
