// <auto-generated />
using System;
using FantasyBasketball.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FantasyBasketball.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FantasyDbContext))]
    [Migration("20260729220305_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.BaselineProjectionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("computed_at");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_version");

                    b.Property<string>("PerMinuteRates")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("per_minute_rates");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("ProjectedGamesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("projected_games_played");

                    b.Property<decimal>("ProjectedMinutesPerGame")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("projected_minutes_per_game");

                    b.Property<string>("ProjectedPerGame")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("projected_per_game");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("baseline_projection", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.DraftPickRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DraftSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_session_id");

                    b.Property<int>("PickNumber")
                        .HasColumnType("integer")
                        .HasColumnName("pick_number");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("DraftSessionId", "PickNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_draft_pick_session_pick_number");

                    b.ToTable("draft_pick", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.DraftSessionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FantasyLeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("fantasy_league_id");

                    b.Property<int>("RoundCount")
                        .HasColumnType("integer")
                        .HasColumnName("round_count");

                    b.HasKey("Id");

                    b.HasIndex("FantasyLeagueId");

                    b.ToTable("draft_session", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.ExternalPlayerIdentityRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ConfirmedByHuman")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmed_by_human");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("linked_at");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_external_player_identity_provider_external_id");

                    b.ToTable("external_player_identity", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.FantasyLeagueRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cadence");

                    b.PrimitiveCollection<string[]>("Categories")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("categories");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("TeamCount")
                        .HasColumnType("integer")
                        .HasColumnName("team_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("fantasy_league", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.NbaTeamRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("abbreviation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("nba_team", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<Guid?>("CurrentTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_team_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.PrimitiveCollection<string[]>("Positions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("positions");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTeamId");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("ix_player_normalized_name");

                    b.ToTable("player", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.RosterSlotRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FantasyLeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("fantasy_league_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.HasKey("Id");

                    b.HasIndex("FantasyLeagueId");

                    b.ToTable("roster_slot", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.ScoringRuleRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FantasyLeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("fantasy_league_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<decimal>("PointsPerUnit")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("points_per_unit");

                    b.Property<string>("Stat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stat");

                    b.HasKey("Id");

                    b.HasIndex("FantasyLeagueId");

                    b.ToTable("scoring_rule", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.SeasonStatLineRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("confidence");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fetched_at");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("games_played");

                    b.Property<decimal>("MinutesPerGame")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("minutes_per_game");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parser_version");

                    b.Property<string>("PerGame")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("per_game");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("RawRecordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_record_hash");

                    b.Property<int>("SeasonEndYear")
                        .HasColumnType("integer")
                        .HasColumnName("season_end_year");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset?>("SourceTimestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("source_timestamp");

                    b.Property<string>("Totals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("totals");

                    b.Property<decimal?>("UsageRate")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("usage_rate");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "SeasonEndYear", "Source")
                        .IsUnique()
                        .HasDatabaseName("ux_season_stat_line_player_season_source");

                    b.ToTable("season_stat_line", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.BaselineProjectionRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerRow", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.DraftPickRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.DraftSessionRow", null)
                        .WithMany()
                        .HasForeignKey("DraftSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerRow", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.DraftSessionRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.FantasyLeagueRow", null)
                        .WithMany()
                        .HasForeignKey("FantasyLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.ExternalPlayerIdentityRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerRow", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.NbaTeamRow", null)
                        .WithMany()
                        .HasForeignKey("CurrentTeamId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.RosterSlotRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.FantasyLeagueRow", null)
                        .WithMany("RosterSlots")
                        .HasForeignKey("FantasyLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.ScoringRuleRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.FantasyLeagueRow", null)
                        .WithMany("ScoringRules")
                        .HasForeignKey("FantasyLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.SeasonStatLineRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerRow", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.FantasyLeagueRow", b =>
                {
                    b.Navigation("RosterSlots");

                    b.Navigation("ScoringRules");
                });
#pragma warning restore 612, 618
        }
    }
}
