// <auto-generated />
using System;
using FantasyBasketball.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FantasyBasketball.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FantasyDbContext))]
    [Migration("20261001211259_ModelVersions")]
    partial class ModelVersions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Identity.FantasyUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsInstanceOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_instance_owner");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("IsInstanceOwner")
                        .IsUnique()
                        .HasFilter("\"is_instance_owner\" = TRUE");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("fantasy_user", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.AdjustedProjectionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<Guid[]>("AppliedContextEventIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("applied_context_event_ids");

                    b.Property<Guid>("BaselineProjectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("baseline_projection_id");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("computed_at");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("confidence");

                    b.Property<decimal>("ContextCertainty")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("context_certainty");

                    b.Property<bool>("HasUnverifiedContext")
                        .HasColumnType("boolean")
                        .HasColumnName("has_unverified_context");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("ProjectedPerGame")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("projected_per_game");

                    b.Property<decimal>("RoleRisk")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("role_risk");

                    b.HasKey("Id");

                    b.HasIndex("BaselineProjectionId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PlayerId", "ComputedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_adjusted_projection_player_computed_at");

                    b.ToTable("adjusted_projection", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.AdpEntryRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AverageDraftPosition")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("average_draft_position");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("confidence");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fetched_at");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parser_version");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("RawRecordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_record_hash");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset?>("SourceTimestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("source_timestamp");

                    b.Property<decimal?>("StandardDeviation")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("standard_deviation");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "FetchedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_adp_entry_player_fetched_at");

                    b.ToTable("adp_entry", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.BaselineProjectionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("computed_at");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_version");

                    b.Property<Guid?>("ObservedStatsId")
                        .HasColumnType("uuid")
                        .HasColumnName("observed_stats_id");

                    b.Property<string>("PerMinuteRates")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("per_minute_rates");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("ProjectedGamesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("projected_games_played");

                    b.Property<decimal>("ProjectedMinutesPerGame")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("projected_minutes_per_game");

                    b.Property<string>("ProjectedPerGame")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("projected_per_game");

                    b.HasKey("Id");

                    b.HasIndex("ObservedStatsId");

                    b.HasIndex("PlayerId");

                    b.ToTable("baseline_projection", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.BoxScoreSnapshotRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("confidence");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fetched_at");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parser_version");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phase");

                    b.Property<DateOnly>("PlayedOn")
                        .HasColumnType("date")
                        .HasColumnName("played_on");

                    b.Property<string>("RawRecordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_record_hash");

                    b.Property<int>("SeasonEndYear")
                        .HasColumnType("integer")
                        .HasColumnName("season_end_year");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset?>("SourceTimestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("source_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("SeasonEndYear", "Source", "GameId", "FetchedAt")
                        .IsDescending(false, false, false, true)
                        .HasDatabaseName("ix_box_score_snapshot_season_latest");

                    b.HasIndex("GameId", "Source", "ParserVersion", "RawRecordHash", "Phase")
                        .IsUnique()
                        .HasDatabaseName("ux_box_score_snapshot_content");

                    b.ToTable("box_score_snapshot", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.ContextEventRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<Guid[]>("AffectedPlayerIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("affected_player_ids");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("ExpectedExpiration")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expected_expiration");

                    b.Property<decimal>("Magnitude")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("magnitude");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("PrimaryPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_player_id");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_name");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("Verification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verification");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("verified_at");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PrimaryPlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("EffectiveFrom", "ExpectedExpiration")
                        .HasDatabaseName("ix_context_event_effective_expiration");

                    b.ToTable("context_event", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.DataImportRunRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FailureDetail")
                        .HasColumnType("text")
                        .HasColumnName("failure_detail");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("finished_at");

                    b.Property<int>("PendingIdentityMatches")
                        .HasColumnType("integer")
                        .HasColumnName("pending_identity_matches");

                    b.Property<int>("RowsWritten")
                        .HasColumnType("integer")
                        .HasColumnName("rows_written");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Source", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_data_import_run_source_started_at");

                    b.ToTable("data_import_run", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.DraftPickRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DraftSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_session_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("PickNumber")
                        .HasColumnType("integer")
                        .HasColumnName("pick_number");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("DraftSessionId", "PickNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_draft_pick_session_pick_number");

                    b.ToTable("draft_pick", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.DraftSessionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FantasyLeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("fantasy_league_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("RoundCount")
                        .HasColumnType("integer")
                        .HasColumnName("round_count");

                    b.Property<int>("TeamCount")
                        .HasColumnType("integer")
                        .HasColumnName("team_count");

                    b.Property<int>("UserSlot")
                        .HasColumnType("integer")
                        .HasColumnName("user_slot");

                    b.HasKey("Id");

                    b.HasIndex("FantasyLeagueId");

                    b.HasIndex("OwnerId");

                    b.ToTable("draft_session", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.ExternalPlayerIdentityRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ConfirmedByHuman")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmed_by_human");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("linked_at");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ux_external_player_identity_player_provider");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_external_player_identity_provider_external_id");

                    b.ToTable("external_player_identity", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.FantasyLeagueRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cadence");

                    b.PrimitiveCollection<string[]>("Categories")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("categories");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("TeamCount")
                        .HasColumnType("integer")
                        .HasColumnName("team_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int>("WeeklyAcquisitionLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(7)
                        .HasColumnName("weekly_acquisition_limit");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("fantasy_league", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.FantasyValueRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AdjustedProjectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("adjusted_projection_id");

                    b.Property<DateTimeOffset?>("ComputedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("computed_at");

                    b.Property<Guid>("FantasyLeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("fantasy_league_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<decimal>("PerGame")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("per_game");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<Guid?>("PublicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("publication_id");

                    b.Property<string>("ScoringProfile")
                        .HasColumnType("text")
                        .HasColumnName("scoring_profile");

                    b.Property<decimal>("SeasonTotal")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("season_total");

                    b.HasKey("Id");

                    b.HasIndex("AdjustedProjectionId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("FantasyLeagueId", "PlayerId", "ComputedAt")
                        .IsDescending(false, false, true);

                    b.HasIndex("PlayerId", "FantasyLeagueId", "AdjustedProjectionId")
                        .HasDatabaseName("ix_fantasy_value_player_league_adjusted");

                    b.ToTable("fantasy_value", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.LeagueEligibilityRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FantasyLeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("fantasy_league_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.PrimitiveCollection<string[]>("Positions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("positions");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("FantasyLeagueId", "PlayerId")
                        .IsUnique();

                    b.ToTable("league_player_eligibility", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.LeagueRosterEntryRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LeagueTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_team_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("LeagueTeamId", "PlayerId")
                        .IsUnique();

                    b.ToTable("league_roster_entry", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.LeagueTeamRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FantasyLeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("fantasy_league_id");

                    b.Property<bool>("IsUsersTeam")
                        .HasColumnType("boolean")
                        .HasColumnName("is_users_team");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("FantasyLeagueId", "Ordinal")
                        .IsUnique();

                    b.ToTable("league_team", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.ModelVersionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CardMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("card_markdown");

                    b.Property<DateTimeOffset>("FittedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fitted_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Metrics")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metrics");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_name");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.PrimitiveCollection<int[]>("TrainSeasonEndYears")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("train_season_end_years");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ModelName")
                        .IsUnique()
                        .HasDatabaseName("ux_model_version_active_per_model")
                        .HasFilter("\"is_active\"");

                    b.HasIndex("ModelName", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_model_version_name_version");

                    b.ToTable("model_version", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.NbaGameRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("integer")
                        .HasColumnName("away_score");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("away_team_id");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("confidence");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fetched_at");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("integer")
                        .HasColumnName("home_score");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_team_id");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parser_version");

                    b.Property<string>("RawRecordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_record_hash");

                    b.Property<int>("SeasonEndYear")
                        .HasColumnType("integer")
                        .HasColumnName("season_end_year");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset?>("SourceTimestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("source_timestamp");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_nba_game_source_external_id");

                    b.ToTable("nba_game", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.NbaTeamRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("abbreviation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique()
                        .HasDatabaseName("ux_nba_team_abbreviation");

                    b.ToTable("nba_team", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.NbaTeamSourceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("confidence");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fetched_at");

                    b.Property<Guid>("NbaTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("nba_team_id");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parser_version");

                    b.Property<string>("RawRecordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_record_hash");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset?>("SourceTimestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("source_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("NbaTeamId");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_nba_team_source_source_external_id");

                    b.ToTable("nba_team_source", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.ObservedStatsRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AsOf")
                        .HasColumnType("timestamptz")
                        .HasColumnName("as_of");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("SeasonEndYear")
                        .HasColumnType("integer")
                        .HasColumnName("season_end_year");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "AsOf")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_observed_stats_player_as_of");

                    b.HasIndex("PlayerId", "SeasonEndYear", "Source");

                    b.ToTable("observed_stats", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.PendingIdentityMatchRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<Guid[]>("CandidatePlayerIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("candidate_player_ids");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ExternalId")
                        .HasDatabaseName("ix_pending_identity_match_provider_external_id");

                    b.ToTable("pending_identity_match", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerAvailabilityRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyPart")
                        .HasColumnType("text")
                        .HasColumnName("body_part");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("confidence");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parser_version");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("RawRecordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_record_hash");

                    b.Property<DateTimeOffset?>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset?>("SourceTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_timestamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Source")
                        .IsUnique();

                    b.ToTable("player_availability", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerContextImpactRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AssistShareDelta")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("assist_share_delta");

                    b.Property<Guid>("ContextEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("context_event_id");

                    b.Property<bool>("IsOverridden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_overridden");

                    b.Property<decimal>("MinutesDelta")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("minutes_delta");

                    b.Property<DateTimeOffset?>("OverriddenAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("overridden_at");

                    b.Property<Guid?>("OverrideUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("override_user_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<decimal>("ProjectionConfidenceDelta")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("projection_confidence_delta");

                    b.Property<decimal>("ReboundShareDelta")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("rebound_share_delta");

                    b.Property<decimal>("RoleRiskDelta")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("role_risk_delta");

                    b.Property<decimal>("ShotVolumeDelta")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("shot_volume_delta");

                    b.Property<decimal>("UsageDelta")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("usage_delta");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ContextEventId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ux_context_impact_event_player");

                    b.ToTable("player_context_impact", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerGameStatRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("confidence");

                    b.Property<bool>("DidPlay")
                        .HasColumnType("boolean")
                        .HasColumnName("did_play");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fetched_at");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parser_version");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("RawRecordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_record_hash");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset?>("SourceTimestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("source_timestamp");

                    b.Property<string>("Statistics")
                        .HasColumnType("jsonb")
                        .HasColumnName("statistics");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_player_game_stat_player");

                    b.HasIndex("SnapshotId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ux_player_game_stat_snapshot_player");

                    b.ToTable("player_game_stat", null, t =>
                        {
                            t.HasCheckConstraint("ck_player_game_stat_appearance", "(did_play AND statistics IS NOT NULL) OR (NOT did_play AND statistics IS NULL)");
                        });
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<Guid?>("CurrentTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_team_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.PrimitiveCollection<string[]>("Positions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("positions");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTeamId");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("ix_player_normalized_name");

                    b.ToTable("player", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.RecommendationEvidenceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<decimal?>("Magnitude")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("magnitude");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Polarity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("polarity");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_id");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statement");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RecommendationId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_recommendation_evidence_ordinal");

                    b.ToTable("recommendation_evidence", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.RecommendationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("confidence");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<decimal>("Score")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("score");

                    b.Property<Guid?>("SubjectPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_player_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SubjectPlayerId");

                    b.ToTable("recommendation", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.RosterSlotRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FantasyLeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("fantasy_league_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.HasIndex("FantasyLeagueId");

                    b.HasIndex("OwnerId");

                    b.ToTable("roster_slot", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.ScoringRuleRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FantasyLeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("fantasy_league_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<decimal>("PointsPerUnit")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("points_per_unit");

                    b.Property<string>("Stat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stat");

                    b.HasKey("Id");

                    b.HasIndex("FantasyLeagueId");

                    b.HasIndex("OwnerId");

                    b.ToTable("scoring_rule", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.SeasonStatLineRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("confidence");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fetched_at");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("games_played");

                    b.Property<decimal>("MinutesPerGame")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("minutes_per_game");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parser_version");

                    b.Property<string>("PerGame")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("per_game");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("RawRecordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_record_hash");

                    b.Property<int>("SeasonEndYear")
                        .HasColumnType("integer")
                        .HasColumnName("season_end_year");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset?>("SourceTimestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("source_timestamp");

                    b.Property<string>("Totals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("totals");

                    b.Property<decimal?>("UsageRate")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("usage_rate");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "SeasonEndYear", "Source")
                        .IsUnique()
                        .HasDatabaseName("ux_season_stat_line_player_season_source");

                    b.ToTable("season_stat_line", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("identity_role", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("identity_role_claim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("identity_user_claim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("identity_user_login", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("identity_user_role", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("identity_user_token", (string)null);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.AdjustedProjectionRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.BaselineProjectionRow", null)
                        .WithMany()
                        .HasForeignKey("BaselineProjectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FantasyBasketball.Infrastructure.Identity.FantasyUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerRow", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.AdpEntryRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerRow", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.BaselineProjectionRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.ObservedStatsRow", null)
                        .WithMany()
                        .HasForeignKey("ObservedStatsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerRow", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.BoxScoreSnapshotRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.NbaGameRow", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.ContextEventRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Identity.FantasyUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerRow", null)
                        .WithMany()
                        .HasForeignKey("PrimaryPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.NbaTeamRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.DraftPickRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.DraftSessionRow", null)
                        .WithMany()
                        .HasForeignKey("DraftSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasketball.Infrastructure.Identity.FantasyUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerRow", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.DraftSessionRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.FantasyLeagueRow", null)
                        .WithMany()
                        .HasForeignKey("FantasyLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasketball.Infrastructure.Identity.FantasyUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.ExternalPlayerIdentityRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerRow", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.FantasyLeagueRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Identity.FantasyUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.FantasyValueRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.AdjustedProjectionRow", null)
                        .WithMany()
                        .HasForeignKey("AdjustedProjectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.FantasyLeagueRow", null)
                        .WithMany()
                        .HasForeignKey("FantasyLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasketball.Infrastructure.Identity.FantasyUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerRow", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.LeagueEligibilityRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.FantasyLeagueRow", null)
                        .WithMany()
                        .HasForeignKey("FantasyLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasketball.Infrastructure.Identity.FantasyUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerRow", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.LeagueRosterEntryRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.LeagueTeamRow", null)
                        .WithMany("Entries")
                        .HasForeignKey("LeagueTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasketball.Infrastructure.Identity.FantasyUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerRow", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.LeagueTeamRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.FantasyLeagueRow", null)
                        .WithMany()
                        .HasForeignKey("FantasyLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasketball.Infrastructure.Identity.FantasyUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.NbaGameRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.NbaTeamRow", null)
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.NbaTeamRow", null)
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.NbaTeamSourceRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.NbaTeamRow", null)
                        .WithMany()
                        .HasForeignKey("NbaTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.ObservedStatsRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.SeasonStatLineRow", null)
                        .WithMany()
                        .HasForeignKey("PlayerId", "SeasonEndYear", "Source")
                        .HasPrincipalKey("PlayerId", "SeasonEndYear", "Source")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerAvailabilityRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerRow", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerContextImpactRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.ContextEventRow", null)
                        .WithMany("Impacts")
                        .HasForeignKey("ContextEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasketball.Infrastructure.Identity.FantasyUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerRow", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerGameStatRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerRow", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.BoxScoreSnapshotRow", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.NbaTeamRow", null)
                        .WithMany()
                        .HasForeignKey("CurrentTeamId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.RecommendationEvidenceRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Identity.FantasyUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.RecommendationRow", null)
                        .WithMany("Evidence")
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.RecommendationRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Identity.FantasyUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerRow", null)
                        .WithMany()
                        .HasForeignKey("SubjectPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.RosterSlotRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.FantasyLeagueRow", null)
                        .WithMany("RosterSlots")
                        .HasForeignKey("FantasyLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasketball.Infrastructure.Identity.FantasyUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.ScoringRuleRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.FantasyLeagueRow", null)
                        .WithMany("ScoringRules")
                        .HasForeignKey("FantasyLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasketball.Infrastructure.Identity.FantasyUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.SeasonStatLineRow", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Persistence.Entities.PlayerRow", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Identity.FantasyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Identity.FantasyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasketball.Infrastructure.Identity.FantasyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("FantasyBasketball.Infrastructure.Identity.FantasyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.ContextEventRow", b =>
                {
                    b.Navigation("Impacts");
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.FantasyLeagueRow", b =>
                {
                    b.Navigation("RosterSlots");

                    b.Navigation("ScoringRules");
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.LeagueTeamRow", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("FantasyBasketball.Infrastructure.Persistence.Entities.RecommendationRow", b =>
                {
                    b.Navigation("Evidence");
                });
#pragma warning restore 612, 618
        }
    }
}
